# Generated by Django 6.0.4 on 2026-07-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP da instituição (apenas para professores)', max_length=9, null=True),
        ),
    ]
