# Generated by Django 6.0.6 on 2026-08-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_cep'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='idx_customuser_role'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['cep'], name='idx_customuser_cep'),
        ),
    ]
