# Generated by Django 6.0.7 on 2026-09-08 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_and_more'),
        ('courses', '0002_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instituicao',
            field=models.ForeignKey(blank=True, help_text='Instituição usada como referência de geolocalização.', limit_choices_to={'ativa': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='courses.instituicao'),
        ),
    ]
