# Generated by Django 6.0.6 on 2026-08-11 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('carga_horaria', models.IntegerField(help_text='Carga horária total em horas')),
                ('frequencia_minima', models.IntegerField(default=75, help_text='Percentual mínimo de frequência para aprovação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(limit_choices_to={'role': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('semestre', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('link_acesso', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='courses.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='courses.turma')),
            ],
        ),
        migrations.CreateModel(
            name='TurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'role': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='courses.turma')),
            ],
            options={
                'verbose_name': 'Turma Aluno',
                'verbose_name_plural': 'Turmas Alunos',
            },
        ),
        migrations.AddIndex(
            model_name='materia',
            index=models.Index(fields=['nome'], name='courses_mat_nome_4db496_idx'),
        ),
        migrations.AddIndex(
            model_name='materia',
            index=models.Index(fields=['professor'], name='courses_mat_profess_aad081_idx'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['ativa'], name='courses_tur_ativa_d3481e_idx'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['ano', 'semestre'], name='courses_tur_ano_e20afd_idx'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['materia', 'ativa'], name='courses_tur_materia_e86e01_idx'),
        ),
        migrations.AddIndex(
            model_name='aula',
            index=models.Index(fields=['data'], name='courses_aul_data_20d0eb_idx'),
        ),
        migrations.AddIndex(
            model_name='aula',
            index=models.Index(fields=['turma', 'data'], name='courses_aul_turma_i_90c672_idx'),
        ),
        migrations.AddIndex(
            model_name='aula',
            index=models.Index(fields=['criada_em'], name='courses_aul_criada__ee3216_idx'),
        ),
        migrations.AddIndex(
            model_name='turmaaluno',
            index=models.Index(fields=['aluno'], name='courses_tur_aluno_i_00c89d_idx'),
        ),
        migrations.AddIndex(
            model_name='turmaaluno',
            index=models.Index(fields=['data_entrada'], name='courses_tur_data_en_1f1645_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='turmaaluno',
            unique_together={('turma', 'aluno')},
        ),
    ]
