# Generated by Django 6.0.7 on 2026-09-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('pais', models.CharField(default='Brasil', max_length=80)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('radius_meters', models.PositiveIntegerField(default=100)),
                ('geocodificada_em', models.DateTimeField(blank=True, null=True)),
                ('geocoding_source', models.CharField(blank=True, default='', max_length=100)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cidade', 'estado'], name='courses_ins_cidade_5fac09_idx'), models.Index(fields=['ativa'], name='courses_ins_ativa_4eae9e_idx')],
            },
        ),
    ]
