# Generated by Django 6.0.6 on 2026-08-11 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoChamada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token_atual', models.CharField(blank=True, max_length=100, unique=True)),
                ('token_expira_em', models.DateTimeField()),
                ('ativa', models.BooleanField(default=True)),
                ('iniciada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('professor_latitude', models.FloatField()),
                ('professor_longitude', models.FloatField()),
                ('professor_radius_meters', models.PositiveIntegerField(default=100)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='courses.aula')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registrada_em', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('localizacao_capturada_em', models.DateTimeField(auto_now_add=True)),
                ('webauthn_verified', models.BooleanField(default=False)),
                ('valida', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to=settings.AUTH_USER_MODEL)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='attendance.sessaochamada')),
            ],
        ),
        migrations.AddIndex(
            model_name='sessaochamada',
            index=models.Index(fields=['ativa'], name='idx_sessaochamada_ativa'),
        ),
        migrations.AddIndex(
            model_name='sessaochamada',
            index=models.Index(fields=['aula', 'ativa'], name='idx_sessaochamada_aula_ativa'),
        ),
        migrations.AddIndex(
            model_name='sessaochamada',
            index=models.Index(fields=['token_expira_em'], name='idx_sessaochamada_token_expira_em'),
        ),
        migrations.AddIndex(
            model_name='presenca',
            index=models.Index(fields=['valida'], name='idx_presenca_valida'),
        ),
        migrations.AddIndex(
            model_name='presenca',
            index=models.Index(fields=['aluno', 'registrada_em'], name='idx_presenca_aluno_registrada_em'),
        ),
        migrations.AddIndex(
            model_name='presenca',
            index=models.Index(fields=['sessao'], name='idx_presenca_sessao'),
        ),
        migrations.AddIndex(
            model_name='presenca',
            index=models.Index(fields=['sessao', 'aluno', 'valida'], name='idx_presenca_sessao_aluno_valida'),
        ),
        migrations.AlterUniqueTogether(
            name='presenca',
            unique_together={('sessao', 'aluno')},
        ),
    ]
