# Generated by Django 6.0.6 on 2026-08-11 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(max_length=128, unique=True)),
                ('tipo', models.CharField(choices=[('register', 'Registro'), ('authenticate', 'Autenticação')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consumido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(max_length=512, unique=True)),
                ('public_key', models.TextField()),
                ('public_key_alg', models.IntegerField(default=-7)),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('nickname', models.CharField(blank=True, default='', max_length=80)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='presenca',
            new_name='idx_pres_aluno_reg',
            old_name='idx_presenca_aluno_registrada_em',
        ),
        migrations.RenameIndex(
            model_name='presenca',
            new_name='idx_pres_ses_aln_val',
            old_name='idx_presenca_sessao_aluno_valida',
        ),
        migrations.RenameIndex(
            model_name='sessaochamada',
            new_name='idx_sessao_ativa',
            old_name='idx_sessaochamada_ativa',
        ),
        migrations.RenameIndex(
            model_name='sessaochamada',
            new_name='idx_sessao_aula_ativa',
            old_name='idx_sessaochamada_aula_ativa',
        ),
        migrations.RenameIndex(
            model_name='sessaochamada',
            new_name='idx_sessao_token_exp',
            old_name='idx_sessaochamada_token_expira_em',
        ),
        migrations.AddField(
            model_name='webauthnchallenge',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webauthncredential',
            name='aluno',
            field=models.ForeignKey(limit_choices_to={'role': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='webauthnchallenge',
            index=models.Index(fields=['challenge'], name='attendance__challen_234bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='webauthnchallenge',
            index=models.Index(fields=['aluno', 'tipo'], name='attendance__aluno_i_190a40_idx'),
        ),
        migrations.AddIndex(
            model_name='webauthncredential',
            index=models.Index(fields=['aluno'], name='attendance__aluno_i_33e55f_idx'),
        ),
    ]
