# Generated by Django 6.0.7 on 2026-09-08 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_webauthnchallenge_webauthncredential_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='webauthnchallenge',
            index=models.Index(fields=['criado_em'], name='attendance__criado__b7db6a_idx'),
        ),
    ]
