# Generated by Django 6.0.4 on 2026-04-23 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'role': 'PROFESSOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.classgroup'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.classgroup'),
        ),
        migrations.AddField(
            model_name='subject',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'role': 'PROFESSOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('class_group', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('subject', 'name')},
        ),
    ]
